### ISSUE TITLE
creation of templates within vagrant chooses wrong template

### ISSUE THREAD

**Issue by joaocc** [Mic92/ansible-lxc#4]
Hi,
I have been observing a weird behavior with ansible-lxc.

My playbook creates a set of containers, starting with a template based on "ubuntu-cloud" / trusty.

Everything runs fine when I do this in a running VM (in this case Vagrant) - LXC container is created with the right template.

However, when I run the exact same playbook as part of vagrant.provision.shell, the template reverts back to "ubuntu" (the default).

Some snippets.

```
container_cloudinit_userdata: ""
my_containers: 
 - name: Template-1404
    template: "ubuntu-cloud"
    template_options: --release trusty {{container_cloudinit_userdata}}
```

```
- name: create containers 
  sudo: yes
  lxc-container: 
    name: "{{ item.name }}"
    template: ubuntu-cloud
    backing_store: "{{item.backing_store|default('dir') }}"
    template_options: "{{ item.template_options|default('') }}"
    state: "stopped"
    container_log: true
  with_items: my_containers

```

The host VM is "ubuntu/trusty64" from Vagrant.

Any ideas?
Thx
